[project]
name = "funcshauns"
version = "0.1.0.2"  # Increment version
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shaun Porwal", email = "shaun.porwal@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = []

