[tool.poetry]
name = "funcshauns"
version = "0.1.0.5"
description = "Add your description here"
authors = ["Shaun Porwal <shaun.porwal@gmail.com>"]
readme = "README.md"
packages = [{ include = "funcshauns", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.4"
ruff = ">=0.8.4"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
