[project]
name = "funcshauns"
version = "0.1.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shaun Porwal", email = "shaun.porwal@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
