name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  # Run tests for Python 3.11
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Tox
      - name: Install Tox
        run: pip install tox

      # Run Tox Tests
      - name: Run Tests
        run: tox -e py311

  # Code formatting check with black
  format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Tox
      - name: Install Tox
        run: pip install tox

      # Run Formatting Check
      - name: Run Formatting Check
        run: tox -e format

  # Publish to Test PyPI on pushes to main
  publish-to-test-pypi:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Tox and dependencies
        run: pip install tox

      - name: Publish to Test PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: tox -e publish-test

  # Publish to PyPI on tag creation
  publish-to-pypi:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Tox and dependencies
        run: pip install tox

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: tox -e publish-prod
